-- Fiscal issued NF-e item lines.

CREATE TABLE llx_fiscal_nfe_line(
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	fk_nfe integer NOT NULL,
	fk_product integer,
	position integer DEFAULT 0 NOT NULL,
	numero_item integer NOT NULL,
	codigo_produto varchar(80),
	descricao text NOT NULL,
	ncm varchar(8),
	cest varchar(7),
	cfop varchar(4),
	unidade_comercial varchar(6),
	quantidade_comercial double(24,8) DEFAULT 0,
	valor_unitario_comercial double(24,10) DEFAULT 0,
	valor_bruto double(24,8) DEFAULT 0,
	unidade_tributavel varchar(6),
	quantidade_tributavel double(24,8) DEFAULT 0,
	valor_unitario_tributavel double(24,10) DEFAULT 0,
	icms_origem varchar(1),
	icms_situacao_tributaria varchar(3),
	icms_aliquota double(6,3) DEFAULT 0,
	icms_valor double(24,8) DEFAULT 0,
	pis_situacao_tributaria varchar(2),
	pis_aliquota double(6,3) DEFAULT 0,
	pis_valor double(24,8) DEFAULT 0,
	cofins_situacao_tributaria varchar(2),
	cofins_aliquota double(6,3) DEFAULT 0,
	cofins_valor double(24,8) DEFAULT 0,
	informacoes_adicionais text,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer,
	import_key varchar(14)
) ENGINE=innodb;
