-- Fiscal issued NF-e header.

CREATE TABLE llx_fiscal_nfe(
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_soc integer,
	fk_project integer,
	fk_focus_company integer,
	focus_environment varchar(20) DEFAULT 'homologation' NOT NULL,
	focus_ref varchar(128),
	chave_nfe varchar(44),
	modelo varchar(2) DEFAULT '55' NOT NULL,
	serie integer,
	numero integer,
	tipo_documento tinyint DEFAULT 1 NOT NULL,
	finalidade_emissao tinyint DEFAULT 1 NOT NULL,
	natureza_operacao varchar(255) NOT NULL,
	data_emissao datetime,
	data_entrada_saida datetime,
	status integer DEFAULT 0 NOT NULL,
	status_focus varchar(64),
	status_sefaz varchar(64),
	mensagem_sefaz text,
	protocolo varchar(80),
	valor_produtos double(24,8) DEFAULT 0,
	valor_frete double(24,8) DEFAULT 0,
	valor_seguro double(24,8) DEFAULT 0,
	valor_desconto double(24,8) DEFAULT 0,
	valor_total double(24,8) DEFAULT 0,
	request_hash char(64),
	request_summary mediumtext,
	response_summary mediumtext,
	http_code integer,
	caminho_xml varchar(255),
	caminho_danfe varchar(255),
	date_transmission datetime,
	date_authorization datetime,
	note_public text,
	note_private text,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer,
	last_main_doc varchar(255),
	import_key varchar(14),
	model_pdf varchar(255)
) ENGINE=innodb;
